apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
type: Opaque
data:
  accesskey: bWluaW8tYWNjb3NzLWtleQ==  # Replace with your Base64-encoded access key
  secretkey: bWluaW8tc2VjcmV0LWtleQ==  # Replace with your Base64-encoded secret key

